In [1]:
import numpy as np

In [ ]:
%pip install numpy


In [2]:
# creating a numpy array
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [6]:
np.arange(4,10,2) #similar to range(start,stop, step)

array([4, 6, 8])

In [10]:
np.zeros((3,2)) #() is the dimension

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

linspace

In [13]:
# Alternative to arange

np.linspace(0,1,15) # start, end, the number of items we want between the start and end

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

Logarithemic spaced array items 

In [14]:
np.logspace(-2,2,5)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [18]:
# from a function

np.fromfunction(lambda i: i**2,(6,))

# here 6 indicates the number of values to be put into the tuple, no of columns

array([ 0.,  1.,  4.,  9., 16., 25.])

In [25]:
# array operators
x = np.arange(4)
print(x)
x+10 # this is not inplace operation

[0 1 2 3]


array([10, 11, 12, 13])

In [23]:
# scalar multiplication and addition
print(x*2)

[0 2 4 6]


In [24]:
print(x*x)
# [0*0 1*1 2*2 3*3]

[0 1 4 9]


In [26]:
x.dot(x)

14

In [29]:
# example of matrix multiplication

x = np.diag(np.arange(4))
print(x)
print("The symbol for matrix multiplication is @: ")
print(x@x)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
The symbol for matrix multiplication is @: 
[[0 0 0 0]
 [0 1 0 0]
 [0 0 4 0]
 [0 0 0 9]]


In [30]:
# append operation - not in place operations

z = np.array([0,1,2,3,4,5])
np.append(z,[7,8,9])

# array name, the list of items to be appended

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [31]:
z

array([0, 1, 2, 3, 4, 5])

# Horizontal stack (hstack) vertical stack (vstack) - np.hstack(tup)

In [34]:
x = np.array([0,0,0])
y = np.array([1,1,1])
z = np.array([2,2,2])
print(np.hstack([x,y,z]))
print(np.vstack([x,y,z]))


[0 0 0 1 1 1 2 2 2]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [3]:
import numpy as np
x = np.array([[1,2,3,4],[15,6,7,8]])
x

array([[ 1,  2,  3,  4],
       [15,  6,  7,  8]])

In [4]:
np.array([1,2,3,4,5],dtype=np.float32)
# 32 indicates the number of bits allocated to store each value

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
np.array([1,2.0,3,4]) # 1,3,4 gets upcasted automatically because of 2.0

array([1., 2., 3., 4.])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3))
# default way of reading is the c programming type...first row and then the column

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

In [9]:
np.random.rand(2,3)

array([[0.72851845, 0.44845688, 0.01744613],
       [0.79294593, 0.9394643 , 0.9043506 ]])

In [11]:
# np.full((2,2),6)  this also gives the same output
np.full((2,2),fill_value= 6)



array([[6, 6],
       [6, 6]])

In [12]:
np.eye(3)  #Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(2,10,2) # exclusive of the end point

array([2, 4, 6, 8])

In [14]:
np.linspace(0,1,20) #inclusive of the end point

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [19]:
a = np.array([[5,10,12],[20,25,30]])
print(a)
print(a.ndim)  # prints its dimension
print(a.shape)
print(a.shape[0]) # gives number of rows
print(a.shape[1]) # gives number of columns
print(a.size)


[[ 5 10 12]
 [20 25 30]]
2
(2, 3)
2
3
6


reshape

In [27]:
x = np.array([3,4,5,6,7,8])
print(x,"\n")
print(np.reshape(x,(3,2)),"\n") 
print(x,"\n")

print(x.reshape(2,3)) #another way of reshaping
x


[3 4 5 6 7 8] 

[[3 4]
 [5 6]
 [7 8]] 

[3 4 5 6 7 8] 

[[3 4 5]
 [6 7 8]]


array([3, 4, 5, 6, 7, 8])

In [33]:
a = np.array([1,2,3,4,5,6])
print(np.reshape(a,(3,-1)),"\n") # automatically decides the number of columns 
print(np.reshape(a,(-1,3)))

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 3]
 [4 5 6]]


flatten() and ravel()

In [44]:
a = np.ones((2,2))
# flatten() - deep copy
# ravel() - shallow copy
print(a)

b = a.flatten()
c = a.ravel()
print("b = " ,b.shape)
print("c = ",c.shape)

print(b,"\n",c)

b[0] = 0
print(f"\nAfter altering b array, \n a =  {a} \n and b = {b}")

c[0] = 5
print(f"\nAfter altering c array, \n a =  {a} \n and c = {c}")


[[1. 1.]
 [1. 1.]]
b =  (4,)
c =  (4,)
[1. 1. 1. 1.] 
 [1. 1. 1. 1.]

After altering b array, 
 a =  [[1. 1.]
 [1. 1.]] 
 and b = [0. 1. 1. 1.]

After altering c array, 
 a =  [[5. 1.]
 [1. 1.]] 
 and c = [5. 1. 1. 1.]


Transpose

In [46]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape,"\n")

b = np.transpose(a)
print(b)
print(b.shape)


[[1 2 3]
 [4 5 6]]
(2, 3) 

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [50]:
# Expanding the dimensions of the given numpy array

a = np.array([1,2,3])
print(a,"\n",a.shape,"\n")

b = np.expand_dims(a,axis=0) # axis = 0 means column and 1 is row 
print(b)
print(b.shape,"\n")

c = np.expand_dims(a,axis=1) # axis = 0 means column and 1 is row 
print(c)
print(c.shape,"\n")

[1 2 3] 
 (3,) 

[[1 2 3]]
(1, 3) 

[[1]
 [2]
 [3]]
(3, 1) 



Squeeze dimension

In [56]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a)
print(a.shape,"\n") # it indicates 1 entry of 2X3 matrix

b = np.squeeze(a,axis=0)
print(b)
print(b.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3) 

[[1 2 3]
 [4 5 6]]
(2, 3)


slicing and indexing

In [58]:
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])
print(a[:6:2]) # from the start
print(a[1::2]) # till the end
print(a[1:6:]) # default step size of one is taken



[2 4]
[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [59]:
# 2D array - indexing

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,0])
print(a[1,2])


[[1 2 3]
 [4 5 6]]
1
6


In [69]:
# 2D array slicing

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(a,"\n")
print(a[:,1:2],"\n") # a[row,column] so here all the rows are selected :,
#  columns only 1 is selected
print(a[:,1:3],"\n")

# to get only first row elements
print(a[:1,:],"\n")

# alternate columns from first row
print(a[:,::2],"\n")

# alternate rows from first row
print(a[::2,:],"\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2]
 [5]
 [8]] 

[[2 3]
 [5 6]
 [8 9]] 

[[1 2 3]] 

[[1 3]
 [4 6]
 [7 9]] 

[[1 2 3]
 [7 8 9]] 



In [5]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.shape)
print(a[:,-1])
print(a[:,-1:-3:-1]) #prints the last two rows, in reverse order, thus step is -1


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[ 5 10]
[[ 5  4]
 [10  9]]


In [9]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Original Array\n",a)
print("\nReversed array\n",a[::-1,::-1])

Original Array
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reversed array
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [12]:
y = np.arange(42).reshape(6,7)
print(y)
print(y[0])
print(y[1])
print(y[3])

# printing the first column
print("\n",y[:,:1])



[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[0 1 2 3 4 5 6]
[ 7  8  9 10 11 12 13]
[21 22 23 24 25 26 27]

 [[ 0]
 [ 7]
 [14]
 [21]
 [28]
 [35]]


In [14]:
# printing only the 3rd column
# print(y[:,2:3])
print(y[:,2])  #both of these will just print the 3rd column


[ 2  9 16 23 30 37]


In [16]:
print(y[2,3]) #random

17


In [17]:
# print the first 3 elements of the second column

print(y)
print(y[:3,1])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[ 1  8 15]


In [18]:
# portion of elements from second and third column

print(y[1:5,1:3])

[[ 8  9]
 [15 16]
 [22 23]
 [29 30]]


In [19]:
# 3X3 subarray from 17th to 33
print(y[2:5,3:6])

[[17 18 19]
 [24 25 26]
 [31 32 33]]


In [20]:
# print every second row from the first row

print(y[::2]) # column need not be specified if there is no restriction

[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]


In [22]:
# print every second column starting from the first column
print(y,"\n")
print(y[:,::2])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]] 

[[ 0  2  4  6]
 [ 7  9 11 13]
 [14 16 18 20]
 [21 23 25 27]
 [28 30 32 34]
 [35 37 39 41]]


In [24]:
# 3D array slicing and indexing
y = np.arange(45).reshape(3,3,5)
y
# here axis zero is all the 3 sheets
# axis 1 is the individual sheets
# axis 2 is the columns


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [25]:
print(y[0]) # prints the first sheet

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [26]:
print(y[0][1]) # second 

[5 6 7 8 9]


In [28]:
print(y[1][1][2])

22


In [30]:
# slicing - return first rows for the last 2D arrays
# y[1:2][0][:] this wont work

y[1:,0]

array([[15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34]])

In [32]:
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [31]:
# slice through both columns and rows 
y[1:,0:2,1:4] # sheets, rows and columns

array([[[16, 17, 18],
        [21, 22, 23]],

       [[31, 32, 33],
        [36, 37, 38]]])

In [34]:
# create a (3,3,3) 3d array with values from 0 to 26

arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
print(arr[0,2:,:]) # last row of first sheet
arr[0,2]

[[6 7 8]]


array([6, 7, 8])

In [42]:
# second row of first and second sheet
print(arr[0:2,1,:])
arr[0:2,1]

[[ 3  4  5]
 [12 13 14]]


array([[ 3,  4,  5],
       [12, 13, 14]])

In [45]:
# last column of all 3 sheets
print(arr[:,:,2:])
arr[:,:,2]

[[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]

 [[20]
  [23]
  [26]]]


array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [1]:
import numpy as np
a = np.arange(1,11).reshape(2,5)
print(a)
print("vertically: ",np.flip(a,axis=1)) # across row entries
print("horizontally: ",np.flip(a,axis=0)) # across column entries


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
vertically:  [[ 5  4  3  2  1]
 [10  9  8  7  6]]
horizontally:  [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [2]:
a = np.arange(0,5)
a = np.arange(0,5)
b = np.arange(5,10)
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[0 1 2 3 4]
[5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
ones = np.array([[1,1,1],[1,1,1]])
n2 = np.array([[1,1,1],[1,1,1]]) * 9
print(n2)
nines = np.array([[9,9,9],[9,9,9]])
x =np.concatenate([ones,nines],axis=0)
y = np.concatenate([ones,nines],axis=1)
print(x)
print(y)


[[9 9 9]
 [9 9 9]]
[[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]
[[1 1 1 9 9 9]
 [1 1 1 9 9 9]]


In [11]:
a = np.arange(5,12,2)
print(a)
print(a-5)
print(a+5)
print(a*5)
print(a/5)
print(a**2)


[ 5  7  9 11]
[0 2 4 6]
[10 12 14 16]
[25 35 45 55]
[1.  1.4 1.8 2.2]
[ 25  49  81 121]


Mean median std


In [13]:
a = np.arange(5,15,2)
print(a)
print("mean",np.mean(a))
print("Standard deviation",np.std(a))
print("median: ",np.median(a))

[ 5  7  9 11 13]
mean 9.0
Standard deviation 2.8284271247461903
median:  9.0


In [15]:
# min and max along the axis

a = np.array([[1,6],[4,10]])
print(a)
print(np.min(a,axis=0))
print(np.min(a,axis=1))


[[ 1  6]
 [ 4 10]]
[1 6]
[1 4]


In [16]:
a = np.array([[1,6,11,12,0],
              [4,10,12,34,2]])
print(a)
print(np.argmin(a,axis=0)) # because the first row elements are smaller - column wise
print(np.argmin(a,axis=1)) 

[[ 1  6 11 12  0]
 [ 4 10 12 34  2]]
[0 0 0 0 0]
[4 4]


In [18]:
# sum across the axis
a = np.array([[1,6],[4,3],[2,2]])
print(a)
print(np.sum(a,axis = 0))
print(np.sum(a,axis = 1))

[[1 6]
 [4 3]
 [2 2]]
[ 7 11]
[7 7 4]


In [19]:
a = np.array([4,5,6,7])
print(a)
b = np.sum(a,initial=40)
print(b)

[4 5 6 7]
62


In [20]:
a = np.array([[1,6],[4,3],[2,2]])
print(a)
print(np.average(a,axis = 0))
print(np.average(a,axis = 1))


[[1 6]
 [4 3]
 [2 2]]
[2.33333333 3.66666667]
[3.5 3.5 2. ]


In [21]:
a = np.array([[1,6],[4,3],[2,2]])
print(a)
print(np.mean(a,axis = 0))
print(np.mean(a,axis = 1))

[[1 6]
 [4 3]
 [2 2]]
[2.33333333 3.66666667]
[3.5 3.5 2. ]


In [23]:
# array copy
a = np.array([1,2,3,4,5])
x = a.copy()
a[0] = 56
print(a)
print(x)

# view changes the value for both the arrays
a = np.array([1,2,3,4,5])
x = a.view()
a[0] = 56
print(a)
print(x)



[56  2  3  4  5]
[1 2 3 4 5]
[56  2  3  4  5]
[56  2  3  4  5]


In [26]:
# array split
a = np.array([1,2,3,4,5,6])
x = np.split(a,3)
print(x)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [27]:
a = np.array([1,4,2,4,3,4,4])
# indices where 4 is present
x = np.where(a==4)
print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [31]:
a = np.arange(5,26)
print(a)
#index position of even values
x = np.where(a%2==0)
print(x)

# index position of odd values
x = np.where(a%2!=0)
print(x)

# create a seperate array of even values
oddarray = []
for i in x:
  oddarray.append(a[i])

print(oddarray)



[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64),)
(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int64),)


[array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])]

In [32]:
x = np.arange(30)
# seperate array for values greater than 20
indi = np.where(x>20)

gt30 = []
for i in indi:
  gt30.append(x[i])

gt30

[array([21, 22, 23, 24, 25, 26, 27, 28, 29])]