# Numpy

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
#creating  numpy array
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [6]:
np.arange(4)


array([0, 1, 2, 3])

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [12]:
#create los-spaced array item
np.logspace(0,2,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [13]:
#from a function
np.fromfunction(lambda i:i**2,(5,))

array([ 0.,  1.,  4.,  9., 16.])

In [17]:
#array operators, array is a vector and we do scalar ops on it
x=np.arange(4)
x+10 #scalar addition
x*2 #scalar mul

array([0, 2, 4, 6])

In [20]:
x=np.arange(4)
#x+x
x*x

array([0, 1, 4, 9])

In [22]:
x=np.arange(4)
x.dot(x)

14

In [24]:
#example of matrix multiplication, we use '@' for tat
x=np.diag(np.arange(4))
print(x@x)
print(x)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 4 0]
 [0 0 0 9]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [29]:
#append - not in place, first save it to a diff var then print else it doesnt get saved 
z=np.array([0,1,2,3,4,5])
y=np.append(z,[7,8,9])
y

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [36]:
#horizontal stck(hstack, vertical stcak(vstack) - np.hstack(tup)
x=np.array([0,0,0])
y=np.array([1,1,1])
z=np.array([2,2,2])
a=np.hstack([x,y,z])
b=np.vstack([x,y,z])
print(a) 
print(b)

[0 0 0 1 1 1 2 2 2]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
np.array([1,2,3,4,5],dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
np.array([1,2.0,3,4,5]) #array gets converted to the higher type


array([1., 2., 3., 4., 5.])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,3)) #c-type, c prog way of reading the array items 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

In [12]:
np.random.rand(2,3)

array([[0.16979047, 0.48470973, 0.50900214],
       [0.091111  , 0.58072375, 0.60205557]])

In [13]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [14]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(2,10,2) #start, stop, step

array([2, 4, 6, 8])

In [18]:
np.linspace(0,100,10) #start, stop, no of elems

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [22]:
a=np.array([[5,10,12],[20,25,30]])
print(a)
print(a.ndim) #ndim tells us the dimension of the array
print(a.shape) #gives the m*n
print(a.shape[0]) # 0- np of rows
print(a.shape[1]) # 1- no of cols


[[ 5 10 12]
 [20 25 30]]
2
(2, 3)
2
3


In [23]:
a=np.array([[5,10,12],[20,25,30]])
print(a.size)

6


In [30]:
#reshape 
a=np.array([5,10,12,20])
a
y=np.reshape(a,(2,2))
print(y)
a.reshape(2,2)

[[ 5 10]
 [12 20]]


array([[ 5, 10],
       [12, 20]])

In [34]:
a=np.array([1,2,3,4,5,6])
np.reshape(a,(3,-1)) #automatically cals the col
np.reshape(a,(-1,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a=np.ones((2,2))
#flatten() - shallow copy 
#raven() - deep copy
print(a)
b=a.flatten()
c=a.ravel()
print(b.shape)
print(b)
print(c.shape)
print(c)

[[1. 1.]
 [1. 1.]]
(4,)
[1. 1. 1. 1.]
(4,)
[1. 1. 1. 1.]


In [42]:
b[0]=0
print(a)
print(b)

[[1. 1.]
 [1. 1.]]
[0. 1. 1. 1.]
[1. 1. 1. 1.]


In [43]:
c[0]=0
print(a)
print(c)

[[0. 1.]
 [1. 1.]]
[0. 1. 1. 1.]


In [46]:
#transpose
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b=np.transpose(a)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [50]:
#expand the dimensions
a=np.array([1,2,3])
print(a)
print(a.shape)
b=np.expand_dims(a,axis=0) # axis=0 refs to cols 
print(b)
print(b.shape)
c=np.expand_dims(a,axis=1) # axis=1 refs to rows
print(c)
print(c.shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)


In [54]:
a=np.array([[[1,2,3],[4,5,6]]])
print(a)
print(a.shape)
#squeeze dimension
b=np.squeeze(a,axis=0)
print(b)
print(b.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [59]:
#slicing and indexing
a=np.array([1,2,3,4,5,6])
print(a[1:6:2])
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

[2 4 6]
[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [60]:
#2d array
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,0])
print(a[1,2])

[[1 2 3]
 [4 5 6]]
1
6


In [77]:
#slicing on a 2d array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[:,1:3]) #prints that col that is col1 to colN
print(a[:1,:]) #first row vals
print(a[::2,:1]) #alternating rows from first row
print(a[:,::2]) #start:stop:step,start:stop:step

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2 3]]
[[1]
 [7]]
[[1 3]
 [4 6]
 [7 9]]
